Algoritmo "area do retangulo"

Var
  base, altura, area, perimetro: real
  

Inicio
Escreva ("Digite o valor da base: ")
Leia(base)

Escreva ("Digite o valor da altura: ")
Leia (altura)

Escreval// pular linha

Area <- base * altura
perimetro <- (2* base) + (2*altura)

Escreva ("A area do retangulo e : ", area)
Escreval// pular linha
Escreva("o perimetro do retangulo e: ", perimetro)



Fimalgoritmo