Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// aluna   : sara viana

Var
// Seção de Declarações das variáveis 
  salario,novoSalario: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
    escreva("Digite salario atual:     ")
    leia(salario)
    
//calculo salario
    novoSalario:=salario + (salario *(25/100))
    
    escreva("o novo salario é:   ", novoSalario)


Fimalgoritmo